require("user.conf.cmp")
require("user.conf.telescope")
require("user.conf.treesitter")
require("user.conf.autopairs")
require("user.conf.comment")
require("user.conf.gitsigns")
require("user.conf.nvim-tree")
require("user.conf.lualine")
require("user.conf.bufferline")
require("user.conf.toggleterm")
require("user.conf.alpha")
require("user.conf.project")
require("user.conf.indentline")
-- require("user.conf.impatient")
require("user.conf.autocommands")
require("user.conf.aerial")
require("user.conf.whichkey")
